### ISSUE TITLE
Setup the Create-React-App Template

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#1]
## Description 

Setup a Create React App Template. If this is the first time, you will be using React, let me share some information about it. 

Create React App (CRA) is a toolkit that is generally used for setting up React Application with ease along with a lot of features, with a unified CLI. Feel free to read about it on the official [Github Repository](https://github.com/facebook/create-react-app) and on the [Docs](https://create-react-app.dev/docs/getting-started/). This [Article](https://www.sitepoint.com/create-react-app/) can give you more depth about what you will be dealing with. 

## Tools 

- Terminal 
- NodeJS
- NPM 

## Directory Structure 

You are supposed to fork the repository and create a branch where you will push your changes. Don't push the entire App on the Root. We will follow this directory structure: 

```
- /client 
-- /src
...
-- index.js
-- registerServiceWorker.js
- .gitignore
- package-lock.json
- package.json

- /server
- /models
-- item.js
- /node.modules
``` 

The Frontend Code will be in a `client` directory while the Backend Code will be in the `server` directory. Keep all the Frontend Code on the Client Directory which you will be supposed to create. Take a look at the Boilerplate Code and replace it with a simple Heading Tag which says: `All Notes App`.

**Comment by priyalweb** [comment]
Hey, can you assign me this issue?
