### ISSUE TITLE
Create the Login/Signup Page Design

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#10]
## Description

Create the Login/Signup Page Design in a widely-supported Design Software (Adobe XD/Figma).

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by pooja-gera** [comment]
PR made.
