### ISSUE TITLE
Design a 404 Page for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#11]
## Description 

Add a 404 Page to keep a visitor on your site even if he/she hits a page that doesn't exist. This would also help us to change the Bad User experience to a positive one by adding some links to that 404 page so that the visitor can navigate to some other page.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by pooja-gera** [comment]
PR made.
