### ISSUE TITLE
Design a Profile Page for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#13]
## Description 

Design a Profile Page which consists of the User Details along with the Notes they have uploaded.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by Mudra-surana** [comment]
https://xd.adobe.com/view/f3420316-c279-49c3-a5d2-4801a9538d93-a611/

**Comment by singhakshita** [comment]
hey i am completely new to open source contribution , can you assign me this task ,i ll try my best
