### ISSUE TITLE
Design a Splash Screen

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#14]
## Description 

Design a Splash Screen which can either an animation or a GIF which can serve as a loading screen to give the end-user immediate feedback that an application is starting and loading in the background.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by pccoder-2000** [comment]
I would like to work on this issue :)

**Comment by HarshCasper** [comment]
@pccoder-2000 Thanks for taking this up. Next time, you can use `/assign` to automatically take up the Issue.
