### ISSUE TITLE
Setup the NodeJS and Express App

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#2]
## Description

Setup the NodeJS and Express Template. There are a lot of NodeJS and Express Boilerplates available on Open-Source [here](https://github.com/topics/nodejs-boilerplate) and you can feel free to pick any one of them. 

You can create your template, by following this [article](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment) and have a simple API Route that returns a sample JSON Message. 

## Tools 

- Terminal 
- NodeJS
- NPM 

## Directory Structure 

You are supposed to fork the repository and create a branch where you will push your changes. Don't push the entire App on the Root. We will follow this directory structure: 

```
- /client 
-- /src
...
-- index.js
-- registerServiceWorker.js
- .gitignore
- package-lock.json
- package.json

- /server
- /models
-- item.js
- /node.modules
``` 

The Frontend Code will be in a `client` directory while the Backend Code will be in the `server` directory. Keep all the Backend Code on the Server Directory which you will be supposed to create. Take a look at the Boilerplate Code and replace it with a simple route that returns a JSON message.

**Comment by aarushivij** [comment]
Hello @HarshCasper , can  I take up this issue?
Thanks in advance
