### ISSUE TITLE
Develop a User Profile Page for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#35]
## Description

Develop the User Profile Page of the Application. 

## Tutorials 

- [User Profile Page in ReactJS](https://www.youtube.com/watch?v=U88ZUp4IRs4)

## Wireframes

We don't have any wireframes as such for the purpose of the Landing Page. If you would like to come up with your design, please have a consultation with me on the basic features before you move ahead with the same. Since @pooja-gera has designed the previous pages as well, she might be better able to advise on how the profile page would look. 

## Branch Policy 

Make this PR on the `dev` branch. We need to deploy the same to denote the upcoming status of the application. 

cc: @harsha14gupta @priyalweb Let me know if you would like to work on the same. If yes, please self-assign this Issue using the `Assignees` option on the Right.

**Comment by singhakshita** [comment]
hey i want to work on this ,please guide me along ,about what all  features are supposed to be added, i am new to it ,but really want to contribute my best
