### ISSUE TITLE
Create Issue + PR Templates

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#4]
## Description

Create a custom Issue and Pull Request Template.

## Additional Details

- Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

- Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

You can take inspiration from [here](https://github.com/stevemao/github-issue-templates) and check [this](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) out to know how to achieve the same.

**Comment by Sonali12920** [comment]
Assign me this. I would like to contribute.

**Comment by HarshCasper** [comment]
@Sonali12920 Thanks for taking this up. Next time, you can use `/assign` to automatically take up the Issue.
