### ISSUE TITLE
Add DeepSource Static Code Analysis

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#6]
## Description 

Add DeepSource Static Code Analysis on this Repository. 

## Additional Details 

- Fork the Repository (If you haven't already) 
- Go through the official [Documentation](https://deepsource.io/docs/analyzer/javascript.html)
- Setup the `deepsource.toml` on the Root. 
- Make a PR. 

I will activate the analysis from my end to find Bugs and Anti-Patterns at every push.

**Comment by Aaliya7516** [comment]
@HarshCasper please allow me to work on this issue

**Comment by HarshCasper** [comment]
@Aaliya7516 Thanks for taking this up. Next time, you can use `/assign` to automatically take up the Issue.

**Comment by Aaliya7516** [comment]
Okk.. I will try my best
