### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#7]
## Description

Create a Code of Conduct which the Mentors and Participants must abide by. 

## Additional Details

- Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
- Add the required responsibilities for Project Maintainers. 
- Mention the Scope of this Code of Conduct.

**Comment by saloniankita** [comment]
I'd like to work on this issue.
