### ISSUE TITLE
Add a Github Action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/AllNotes#8]
## Description 

Add a Github Action to auto-assign Mentors for every PR. It is a pain sometime to take a look at all the Projects for the PRs made by the Contributors. Getting a nice notification about reviewing a PR would make things easy for me. 

You can take a look at this [Github Action](https://github.com/marketplace/actions/auto-assign-action) for the purpose. Check [this](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) out to know how to achieve the same.

**Comment by m-code12** [comment]
@HarshCasper I would like to take this up.

**Comment by HarshCasper** [comment]
@m-code12 Thanks for taking this up. Next time, you can use `/assign` to automatically take up the Issue.
